// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF_vhnMGwz28N7fIkS_ZtRAY6jzgZw9QQ',
    appId: '1:771662021056:web:437224553dd35ea793c825',
    messagingSenderId: '771662021056',
    projectId: 'flutter-push-notificatio-f2b44',
    authDomain: 'flutter-push-notificatio-f2b44.firebaseapp.com',
    storageBucket: 'flutter-push-notificatio-f2b44.firebasestorage.app',
    measurementId: 'G-EF30L8TVZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEl4zilnlE5aqK-gQ_6GEEuAH7FYk5lgM',
    appId: '1:771662021056:android:e3693d52dca1c05093c825',
    messagingSenderId: '771662021056',
    projectId: 'flutter-push-notificatio-f2b44',
    storageBucket: 'flutter-push-notificatio-f2b44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsNjtip7cYm5wvyh5n07os4HFTK14_aIs',
    appId: '1:771662021056:ios:1e197f849cdb755f93c825',
    messagingSenderId: '771662021056',
    projectId: 'flutter-push-notificatio-f2b44',
    storageBucket: 'flutter-push-notificatio-f2b44.firebasestorage.app',
    iosBundleId: 'com.example.flutterPushNotificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsNjtip7cYm5wvyh5n07os4HFTK14_aIs',
    appId: '1:771662021056:ios:1e197f849cdb755f93c825',
    messagingSenderId: '771662021056',
    projectId: 'flutter-push-notificatio-f2b44',
    storageBucket: 'flutter-push-notificatio-f2b44.firebasestorage.app',
    iosBundleId: 'com.example.flutterPushNotificationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF_vhnMGwz28N7fIkS_ZtRAY6jzgZw9QQ',
    appId: '1:771662021056:web:9c68d687b9f27f1b93c825',
    messagingSenderId: '771662021056',
    projectId: 'flutter-push-notificatio-f2b44',
    authDomain: 'flutter-push-notificatio-f2b44.firebaseapp.com',
    storageBucket: 'flutter-push-notificatio-f2b44.firebasestorage.app',
    measurementId: 'G-PXL4BFKTM5',
  );
}
